# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: go-tei
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    # 以下、magefile.go で依存にしたほうがスッキリする?
    - mage clean
builds:
-
  id: tei
  binary: tei
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  ldflags:
    - -s -w -X github.com/hankei6km/go-tei/cmd/tei/cmd.cmdVer={{.Version}} -X github.com/hankei6km/go-tei/cmd/tei/cmd.cmdCommitHash={{.ShortCommit}}
  main: ./cmd/tei
  hooks:
    post: mage credits
archives:
-
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    # amd64: x86_64
  # name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: zip
  wrap_in_directory: false
  files:
    - LICENSE
    - CREDITS*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: hankei6km
    name: go-tei

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  # name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  # disable: true
