name: test

on:
  push:
    branches:
      - "**"
    tags:
      - "!v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # go-version: ["1.14", "1.15", "1.16.x"]
        # とりあえず除外
        # https://github.com/actions/setup-go/issues/304
        go-version: ["1.15", "1.16.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: |
          go get github.com/magefile/mage

      - name: Test with mage
        run: mage test
